/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import Java.sql.*;
import dao.UsuarioDao;
import logica.UsuarioLogica;
import conexion.Conexion;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Nixon Sanchez
 */
public class JFraLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFrUsuario
     */
    public JFraLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
     private void login() throws SQLException{
        try {
            UsuarioLogica cu = new UsuarioLogica();
            UsuarioDao du = new UsuarioDao();
            cu.setNombre(this.jTFUsuario.getText());
            cu.setContrasenia(this.jPFContrasena.getText());
            int cod = du.existeUsuario(cu);
            if(du.existeUsuario(cu)>0){
                try{
                   
                    JFraMDI a = new JFraMDI();             
                    a.idUsuario = cod;
                    a.show();
                    
                    
                    this.dispose();
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "error" + e);
                }
                }else{
                if(!"".equals(jTFUsuario.getText()) && !"".equals(jPFContrasena.getText())){
                    JOptionPane.showMessageDialog(null, "Usuario o Contraseña no válidos");
                    this.jTFUsuario.requestFocus();
                }
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" +e);
        }
    }
    
    private void validar(){
        if("".equals(this.jTFUsuario.getText()) && "".equals(this.jPFContrasena.getText())) {
            JOptionPane.showMessageDialog(null, "Debe ingresar los datos de inicio de sesión");
            this.jTFUsuario.requestFocus();
        }else if("".equals(this.jPFContrasena.getText())){
            JOptionPane.showMessageDialog(null, "Debe ingresar la contraseña");
            this.jPFContrasena.requestFocus();
        }else if("".equals(this.jTFUsuario.getText())){
            JOptionPane.showMessageDialog(null, "Debe ingresar su nombre de usuario");
            this.jTFUsuario.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFUsuario = new javax.swing.JTextField();
        jBtnIngresar = new javax.swing.JButton();
        jBtnCanselar = new javax.swing.JButton();
        jPFContrasena = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 270, 30));

        jBtnIngresar.setText("Ingresar");
        jBtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 100, 30));

        jBtnCanselar.setText("Cancelar");
        jBtnCanselar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCanselarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCanselar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 100, 30));
        getContentPane().add(jPFContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 270, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 234, 234));
        jLabel2.setText("INICIO DE SESIÓN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Contraseña:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nombre de Usuario:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login/logo.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 220, 130));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/low.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login/arriba.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login/arriba.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 700, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login/fondo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 700, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIngresarActionPerformed
        try{
            validar();
            login();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "usuario o password invalido");
        }
    }//GEN-LAST:event_jBtnIngresarActionPerformed

    private void jBtnCanselarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCanselarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBtnCanselarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFraLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFraLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCanselar;
    private javax.swing.JButton jBtnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPFContrasena;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
