package presentacion;
import conexion.Conexion;
import dao.FacturaDao;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.net.URLDecoder;
import java.sql.Connection;
import logica.FacturaLogica;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
public class JIFBuscarFactura extends javax.swing.JInternalFrame {
    public static int cod ;
    public JIFBuscarFactura() throws SQLException {
        initComponents();
        llenarTabla();
    }
    
    //Metodo de Limpieza de la Tabla de Datos.
    private void limpiarTabla(){
        DefaultTableModel temp = (DefaultTableModel) this.jTbMostrar.getModel(); 

        while (temp.getRowCount() > 0) {
            temp.removeRow(0);
        }
    }
    
    //Metodo de llenado de la Tabla de Datos.
    private void llenarTabla() throws SQLException{
        limpiarTabla();
        FacturaDao dao = new FacturaDao();
        List<FacturaLogica> miLista = dao.getLista(this.jTFFiltro.getText());
        DefaultTableModel tabla = (DefaultTableModel) this.jTbMostrar.getModel();
        miLista.stream().map((FacturaLogica) -> {
            Object [] fila = new Object [6];
            fila[0] = FacturaLogica.getIdFactura();
            fila[1] = FacturaLogica.getRtnCliente();
            fila[2] = FacturaLogica.getNombreCliente();
            fila[3] = FacturaLogica.getApellidoCliente();
            fila[4] = FacturaLogica.getTipoSFactura();
            fila[5] = FacturaLogica.getFechafactura();
            return fila;
        }).forEachOrdered((fila) -> {
            tabla.addRow(fila);
        });  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTbMostrar = new javax.swing.JTable();
        jTFFiltro = new javax.swing.JTextField();
        jBtnR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTbMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodFactura", "RTN Cliente", "Nombre", "Apellido", "Tipo Factura", "Fecha Factura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbMostrarMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTbMostrarMouseReleased(evt);
            }
        });
        jTbMostrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTbMostrarKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTbMostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 690, 210));

        jTFFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFFiltroKeyReleased(evt);
            }
        });
        getContentPane().add(jTFFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 288, -1));

        jBtnR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chart_bar_add.png"))); // NOI18N
        jBtnR.setText("Reporte Cod Factura");
        jBtnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom.png"))); // NOI18N
        jLabel2.setText("Buscar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Valken", 0, 24)); // NOI18N
        jLabel5.setText("Busqueda Factura");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Picture5.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 680, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Picture2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 300, 330));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Evento de la jTextField
    private void jTFFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFFiltroKeyReleased
         try {
            llenarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(JIFCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTFFiltroKeyReleased

    private void jBtnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRActionPerformed
        String path = "";
        try {
            path = getClass().getResource("/reportes/RptFacturaId.jasper").getPath();
            path = URLDecoder.decode(path,"UTF-8");
            Connection cn = Conexion.conectar();
            Map parametros = new HashMap();
            

            parametros.put("cod",cod);

            JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
            JasperPrint imprimir = JasperFillManager.fillReport(reporte,parametros,cn);
            JasperViewer visor = new JasperViewer(imprimir,false);
            

            visor.setTitle("Reporte de Factura");
            visor.setExtendedState(MAXIMIZED_BOTH);
            visor.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Mostrar el reporte: "+e.getMessage());
        }
    }//GEN-LAST:event_jBtnRActionPerformed

    private void jTbMostrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbMostrarKeyPressed
      
    }//GEN-LAST:event_jTbMostrarKeyPressed

    private void jTbMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbMostrarMouseClicked
        try {
            filaSeleccionada();
        } catch (SQLException ex) {
            Logger.getLogger(JIFBuscarFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTbMostrarMouseClicked

    private void jTbMostrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbMostrarMouseReleased
         try {
            filaSeleccionada();
        } catch (SQLException ex) {
            Logger.getLogger(JIFBuscarFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTbMostrarMouseReleased
    private void filaSeleccionada() throws SQLException{
        if (this.jTbMostrar.getSelectedRow() != -1){
        cod = Integer.parseInt(String.valueOf(this.jTbMostrar.getValueAt(this.jTbMostrar.getSelectedRow(), 0)));
       
        }
    }    
    //Metodo principal Main.
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(() -> {
            try{
                new JIFBuscarCliente().setVisible(true);
            }catch (SQLException ex) {
                Logger.getLogger(JIFBuscarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFFiltro;
    private javax.swing.JTable jTbMostrar;
    // End of variables declaration//GEN-END:variables
}
